name: "Deployment of Portfolio - DevSphere"

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy by SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: amitdhangar531
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            if ! command -v git &> /dev/null; then
              sudo apt update && sudo apt install git -y
            fi
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker amitdhangar531
            fi
            if [ ! -d "/home/amitdhangar531/DevSphere" ]; then
              git clone https://AmitDhangarr:${{ secrets.GH_TOKEN }}@github.com/AmitDhangarr/DevSphere.git /home/amitdhangar531/DevSphere
            fi
            cd /home/amitdhangar531/DevSphere
            git pull https://AmitDhangarr:${{ secrets.GH_TOKEN }}@github.com/AmitDhangarr/DevSphere.git main
            cd server
            sudo docker compose up -d --build